/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import dao.DAOProduit;
import dao.DAOTicket;
import dao.DAOVente;
import factory.Factory;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import model.JTableTicket;
import transferObject.Produit;
import transferObject.Transaction;
import transferObject.Vente;

/**
 *
 * @author Himmat
 */
public class JDialogTicket extends javax.swing.JDialog {

    /**
     * Creates new form JDialogTicket
     *
     * @param parent
     * @param titre
     */
    private int idVente;
    NumberFormat formatter = new DecimalFormat("##,##0.00 €");

    public JDialogTicket(java.awt.Frame parent, Transaction trans, String titre) {
        super(parent, titre, true);
        initComponents();
        remplireInfoTicket(trans);
        setLocation(parent.getX() + parent.getWidth() / 3, parent.getY() + parent.getHeight() / 3);
        setVisible(true);
    }

    public JDialogTicket(Transaction trans, java.awt.Dialog parent, String titre) {
        super(parent, titre, true);
        initComponents();
        remplireInfoTicket(trans);
        setLocation(parent.getX() + parent.getWidth() / 3, parent.getY() + parent.getHeight() / 3);
        setVisible(true);
    }

    private void remplireInfoTicket(Transaction trans) {
        this.idVente = trans.getIdVente();
        this.jTextFieldIdCassier.setText(String.valueOf(trans.getIdVendeur()));
        this.jTextFieldTotal.setText(formatter.format(trans.getTotal()));
        this.jTextFieldDate.setText(trans.getDateString());
        myModelTicket.setMyList(daoTicket.selectTicket(idVente));
        
        int nbArticle = 0;
        int nbArticleDif = 0;

        double montantTVA = 0;
        double prixHTVA = 0;
        for (Produit ticket : daoTicket.selectTicket(trans.getIdVente())) {
            nbArticle += ticket.getQuantite();
            montantTVA += ticket.getMontantTva();
            prixHTVA += ticket.getPrixHTVA();
            nbArticleDif++;
        }
        jTextFieldNbArticle.setText(String.valueOf(nbArticle));
        jTextFieldNbArticleDif.setText(String.valueOf(nbArticleDif));
        jTextFieldMontantTVA.setText(formatter.format(montantTVA));
        jTextFieldPrixHTVA.setText(formatter.format(prixHTVA));
        jTextFieldRemise.setText(formatter.format(daoVente.remiseVente(idVente)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMain = new javax.swing.JPanel();
        jButtonModifier = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButtonModifier1 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTicket = new JTable(myModelTicket);
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jTextFieldIdCassier = new javax.swing.JTextField();
        jTextFieldDate = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldNbArticle = new javax.swing.JTextField();
        jTextFieldNbArticleDif = new javax.swing.JTextField();
        jLabelMontantTva = new javax.swing.JLabel();
        jLabelPrixHTVA = new javax.swing.JLabel();
        jTextFieldMontantTVA = new javax.swing.JTextField();
        jTextFieldPrixHTVA = new javax.swing.JTextField();
        jLabelPrixHTVA1 = new javax.swing.JLabel();
        jTextFieldRemise = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldTotal = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelMain.setBackground(new java.awt.Color(175, 210, 245));

        jButtonModifier.setBackground(new java.awt.Color(134, 185, 236));
        jButtonModifier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Actions-view-refresh-icon.png"))); // NOI18N
        jButtonModifier.setText("Modifier");
        jButtonModifier.setEnabled(false);
        jButtonModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifierActionPerformed(evt);
            }
        });
        jButtonModifier.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonModifierKeyPressed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(134, 185, 236));
        jButton10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete-icon.png"))); // NOI18N
        jButton10.setText("Supprimer");
        jButton10.setEnabled(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(134, 185, 236));
        jButton11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete-icon.png"))); // NOI18N
        jButton11.setText("Annuler Vente");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButtonModifier1.setBackground(new java.awt.Color(134, 185, 236));
        jButtonModifier1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Actions-view-refresh-icon.png"))); // NOI18N
        jButtonModifier1.setText("Retour");
        jButtonModifier1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifier1ActionPerformed(evt);
            }
        });
        jButtonModifier1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonModifier1KeyPressed(evt);
            }
        });

        jButton12.setBackground(new java.awt.Color(134, 185, 236));
        jButton12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add-icon.png"))); // NOI18N
        jButton12.setText("Ajouter un article");
        jButton12.setEnabled(false);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jTableTicket);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Vendeur : ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Vente");

        jTextFieldIdCassier.setBackground(new java.awt.Color(204, 255, 204));
        jTextFieldIdCassier.setEnabled(false);

        jTextFieldDate.setBackground(new java.awt.Color(204, 255, 204));
        jTextFieldDate.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Date du ticket : ");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Nom de cassier : ");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Article : ");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Article divers : ");

        jTextFieldNbArticle.setBackground(new java.awt.Color(204, 255, 204));
        jTextFieldNbArticle.setEnabled(false);

        jTextFieldNbArticleDif.setBackground(new java.awt.Color(204, 255, 204));
        jTextFieldNbArticleDif.setEnabled(false);

        jLabelMontantTva.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelMontantTva.setText("Prix TVA :");

        jLabelPrixHTVA.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelPrixHTVA.setText("Prix HTVA :");

        jTextFieldMontantTVA.setBackground(new java.awt.Color(204, 255, 204));
        jTextFieldMontantTVA.setEnabled(false);

        jTextFieldPrixHTVA.setBackground(new java.awt.Color(204, 255, 204));
        jTextFieldPrixHTVA.setEnabled(false);

        jLabelPrixHTVA1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelPrixHTVA1.setText("Remise");

        jTextFieldRemise.setBackground(new java.awt.Color(204, 255, 204));
        jTextFieldRemise.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Prix TTC :");

        jTextFieldTotal.setBackground(new java.awt.Color(204, 255, 204));
        jTextFieldTotal.setEnabled(false);

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addComponent(jButton11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonModifier)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonModifier1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelMainLayout.createSequentialGroup()
                                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jSeparator2)
                                            .addGroup(jPanelMainLayout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jTextFieldDate, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(jLabel1)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainLayout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldIdCassier, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelMainLayout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(52, 52, 52)
                                        .addComponent(jTextFieldNbArticle, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelMontantTva)
                                        .addGap(49, 49, 49)
                                        .addComponent(jTextFieldMontantTVA, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelMainLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldNbArticleDif, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelPrixHTVA)
                                        .addGap(40, 40, 40)
                                        .addComponent(jTextFieldPrixHTVA, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelMainLayout.createSequentialGroup()
                                        .addGap(178, 178, 178)
                                        .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanelMainLayout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                                .addComponent(jTextFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainLayout.createSequentialGroup()
                                                .addComponent(jLabelPrixHTVA1)
                                                .addGap(62, 62, 62)
                                                .addComponent(jTextFieldRemise, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.TRAILING)))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldDate, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5)
                                .addComponent(jTextFieldNbArticle, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelMontantTva)
                                .addComponent(jTextFieldMontantTVA, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)))
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator3)
                    .addComponent(jSeparator4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldIdCassier, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldNbArticleDif, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelPrixHTVA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldPrixHTVA, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldRemise, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPrixHTVA1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonModifier, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonModifier1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifierActionPerformed

        if (jTableTicket.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Sélectionnez d'abord une ligne svp !",
                    "Avertissement", JOptionPane.ERROR_MESSAGE);
        } else {
            
            int qte = Integer.parseInt(JOptionPane.showInputDialog(this,
                    "Donner la qte?", null));
            Produit tick = myModelTicket.getMyList(jTableTicket.getSelectedRow());
            if (qte <= 0) {
                daoTicket.deleteNbProduitVendu(tick.getCodebarre(), idVente);

            } else {
                JOptionPane.showMessageDialog(this, tick.getPrixVente());
                daoTicket.updateTicketQte(qte, idVente, tick.getCodebarre(), tick.getPrixVente());
            }
            myModelTicket.setMyList(daoTicket.selectTicket(idVente));
        }
    }//GEN-LAST:event_jButtonModifierActionPerformed

    private void jButtonModifierKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonModifierKeyPressed

    }//GEN-LAST:event_jButtonModifierKeyPressed

    private void jButtonModifier1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifier1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonModifier1ActionPerformed

    private void jButtonModifier1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonModifier1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonModifier1KeyPressed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed

        if (daoTicket.deleteVente(idVente)) {
            JOptionPane.showMessageDialog(this, "Supprimer avec succès !");
            this.dispose();
        }


    }//GEN-LAST:event_jButton11ActionPerformed
    private boolean dejaDansLeTicket(String codeBarre) {
        boolean exist = false;
        for (Produit ticket : daoTicket.selectTicket(idVente)) {
            if (ticket.getCodebarre().compareTo(codeBarre) == 0) {
                exist = true;
                break;
            }
        }
        return exist;
    }

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        String codeBarre = JOptionPane.showInputDialog(this,
                "Scanner le produit ", null);
        if (codeBarre != null) {

            if (!dejaDansLeTicket(codeBarre)) {
                Produit pro = daoProduit.uneVenteProduit(codeBarre);
                if (pro != null) {
                    double tva = ((pro.getTva() / 100) + 1);
                    double prixHTArt = pro.getPrixVente() / tva;
                    double montantTvaArti = (pro.getPrixVente() - prixHTArt);
                    Vente vente = new Vente(idVente, pro.getCodebarre(), 1, pro.getPrixVente(),
                            prixHTArt, 0, montantTvaArti, pro.getTva(), pro.getPrixVente(), pro.getLibelle());
                    daoVente.insertNbProdVente(vente);
                    myModelTicket.setMyList(daoTicket.selectTicket(idVente));

                }
            } else {
                JOptionPane.showMessageDialog(this, "Ce produit est déjà dans la liste");
            }
        }


    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        if (jTableTicket.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Sélectionnez d'abord une ligne svp !",
                    "Avertissement", JOptionPane.ERROR_MESSAGE);
        } else {
            Produit tick = myModelTicket.getMyList(jTableTicket.getSelectedRow());
            if (daoTicket.deleteNbProduitVendu(tick.getCodebarre(), idVente)) {
                JOptionPane.showMessageDialog(this, "Supprimer avec succès !");
                myModelTicket.setMyList(daoTicket.selectTicket(idVente));
            }
            //supprimerVente(vente);
        }
    }//GEN-LAST:event_jButton10ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButtonModifier;
    private javax.swing.JButton jButtonModifier1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelMontantTva;
    private javax.swing.JLabel jLabelPrixHTVA;
    private javax.swing.JLabel jLabelPrixHTVA1;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTable jTableTicket;
    private javax.swing.JTextField jTextFieldDate;
    private javax.swing.JTextField jTextFieldIdCassier;
    private javax.swing.JTextField jTextFieldMontantTVA;
    private javax.swing.JTextField jTextFieldNbArticle;
    private javax.swing.JTextField jTextFieldNbArticleDif;
    private javax.swing.JTextField jTextFieldPrixHTVA;
    private javax.swing.JTextField jTextFieldRemise;
    private javax.swing.JTextField jTextFieldTotal;
    // End of variables declaration//GEN-END:variables
    private static final DAOTicket daoTicket = Factory.getTicket();
    private static JTableTicket myModelTicket = new JTableTicket(daoTicket.selectTicket(10));
    private static final DAOVente daoVente = Factory.getDAOVente();
    private static final DAOProduit daoProduit = Factory.getDAOProduit();
}
