/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import Utile.MethodeUtile;
import dao.DAOCategorie;
import dao.DAOPrixDeVente;
import dao.DAOProduit;
import factory.Factory;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import model.JTableCategorie;
import transferObject.Categorie;
import transferObject.PrixDeVente;
import transferObject.Produit;

/**
 *
 * @author Fawad
 */
public class JDialogAjouterProduit extends javax.swing.JDialog {

    /**
     * Creates new form JDialogAjouterProduit
     */
    MethodeUtile util = new MethodeUtile();

    public JDialogAjouterProduit(java.awt.Frame parent, String titre) {
        super(parent, titre, true);
        initComponents();
        jLabelIdCat.setVisible(false);
        util.changeFocus(jTextFieldCodeBarre);
        configJTable();
        refresh();
    }

    public JDialogAjouterProduit(java.awt.Frame parent, String titre, Produit pro) {
        super(parent, titre, true);
        initComponents();
        refresh();
        setProduitField(pro);
        configJTable();

        jTextFieldCodeBarre.setEditable(false);
    }

    private void refresh() {

        for (Categorie cat : daoCat.selectCategorie()) {

            jComboBoxCategorie.addItem(cat.getLibelle());
        }
        jLabelNbCat.setText(String.valueOf(daoCat.selectCategorie().size()));
        jLabelNbArticle.setText(String.valueOf(daoProd.selectProduit().size()));
        myModel.setMyList(daoCat.selectCategorie());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelProdPane = new javax.swing.JPanel();
        jTextFieldLibelle = new javax.swing.JTextField();
        jTextFieldCodeBarre = new javax.swing.JTextField();
        jComboBoxCategorie = new javax.swing.JComboBox();
        jTextFieldPrixAchat = new javax.swing.JFormattedTextField();
        jTextFieldPrixVente = new javax.swing.JFormattedTextField();
        jTextFieldStock = new javax.swing.JFormattedTextField();
        jButtonAjouter = new javax.swing.JButton();
        jButtonModifier = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabelNbArticle = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        jPanelInputCateg = new javax.swing.JPanel();
        jButtonaddcat = new javax.swing.JButton();
        jButtonmodifCat = new javax.swing.JButton();
        jTextFieldCatLibelle = new javax.swing.JTextField();
        jTextFieldTva = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabelNbCat = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTableCat = new JTable(myModel);
        jLabelIdCat = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(175, 210, 245));
        jTabbedPane1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        jPanelProdPane.setBackground(new java.awt.Color(175, 210, 245));
        jPanelProdPane.setPreferredSize(new java.awt.Dimension(537, 342));

        jTextFieldLibelle.setBackground(new java.awt.Color(102, 153, 204));
        jTextFieldLibelle.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jTextFieldLibelle.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextFieldCodeBarre.setBackground(new java.awt.Color(102, 153, 204));
        jTextFieldCodeBarre.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jTextFieldCodeBarre.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextFieldCodeBarre.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextFieldCodeBarre.setPreferredSize(new java.awt.Dimension(0, 24));
        jTextFieldCodeBarre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodeBarreActionPerformed(evt);
            }
        });
        jTextFieldCodeBarre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldCodeBarreKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCodeBarreKeyTyped(evt);
            }
        });

        jComboBoxCategorie.setBackground(new java.awt.Color(102, 255, 102));

        jTextFieldPrixAchat.setBackground(new java.awt.Color(102, 153, 204));
        jTextFieldPrixAchat.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextFieldPrixAchat.setText("0.00");
        jTextFieldPrixAchat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldPrixAchat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPrixAchatKeyTyped(evt);
            }
        });

        jTextFieldPrixVente.setBackground(new java.awt.Color(255, 51, 51));
        jTextFieldPrixVente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextFieldPrixVente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldPrixVente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrixVenteActionPerformed(evt);
            }
        });
        jTextFieldPrixVente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPrixVenteKeyTyped(evt);
            }
        });

        jTextFieldStock.setBackground(new java.awt.Color(102, 153, 204));
        jTextFieldStock.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextFieldStock.setText("0");
        jTextFieldStock.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldStockActionPerformed(evt);
            }
        });
        jTextFieldStock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldStockKeyTyped(evt);
            }
        });

        jButtonAjouter.setBackground(new java.awt.Color(102, 153, 204));
        jButtonAjouter.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jButtonAjouter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add-icon.png"))); // NOI18N
        jButtonAjouter.setText("Ajouter");
        jButtonAjouter.setBorder(null);
        jButtonAjouter.setBorderPainted(false);
        jButtonAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjouterActionPerformed(evt);
            }
        });
        jButtonAjouter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonAjouterKeyPressed(evt);
            }
        });

        jButtonModifier.setBackground(new java.awt.Color(102, 153, 204));
        jButtonModifier.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jButtonModifier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Actions-view-refresh-icon.png"))); // NOI18N
        jButtonModifier.setText("Modifier");
        jButtonModifier.setBorder(null);
        jButtonModifier.setBorderPainted(false);
        jButtonModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifierActionPerformed(evt);
            }
        });
        jButtonModifier.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonModifierKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel1.setText("Codebarre du produit :");

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel3.setText("Libellé du produit :");

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel4.setText("Prix achat");

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel5.setText("Prix vente");

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel6.setText("Quantité");

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel7.setText("Catégorie");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Nombre d'articles :");

        jLabelNbArticle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelNbArticle.setText("00000");

        javax.swing.GroupLayout jPanelProdPaneLayout = new javax.swing.GroupLayout(jPanelProdPane);
        jPanelProdPane.setLayout(jPanelProdPaneLayout);
        jPanelProdPaneLayout.setHorizontalGroup(
            jPanelProdPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProdPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelProdPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelProdPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanelProdPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelProdPaneLayout.createSequentialGroup()
                                .addComponent(jButtonAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonModifier, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelProdPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator2)
                                .addComponent(jSeparator1)
                                .addComponent(jSeparator3)
                                .addGroup(jPanelProdPaneLayout.createSequentialGroup()
                                    .addGroup(jPanelProdPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProdPaneLayout.createSequentialGroup()
                                            .addGroup(jPanelProdPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addGap(31, 31, 31))
                                        .addGroup(jPanelProdPaneLayout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addGap(121, 121, 121)))
                                    .addGroup(jPanelProdPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldStock, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanelProdPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jComboBoxCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldPrixVente, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldLibelle, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                                            .addComponent(jTextFieldPrixAchat, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldCodeBarre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                        .addComponent(jSeparator6)
                        .addComponent(jSeparator7))
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelProdPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelProdPaneLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelNbArticle))
                    .addComponent(jSeparator12))
                .addContainerGap())
        );
        jPanelProdPaneLayout.setVerticalGroup(
            jPanelProdPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProdPaneLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanelProdPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelProdPaneLayout.createSequentialGroup()
                        .addGroup(jPanelProdPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabelNbArticle))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelProdPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelProdPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCodeBarre, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelProdPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldLibelle, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelProdPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPrixAchat, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelProdPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPrixVente, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelProdPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldStock, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jPanelProdPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonModifier, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );

        jTabbedPane1.addTab("Ajouter Produit", jPanelProdPane);

        jPanelInputCateg.setBackground(new java.awt.Color(175, 210, 245));
        jPanelInputCateg.setPreferredSize(new java.awt.Dimension(463, 266));

        jButtonaddcat.setBackground(new java.awt.Color(102, 153, 204));
        jButtonaddcat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonaddcat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add-icon.png"))); // NOI18N
        jButtonaddcat.setText("Ajouter");
        jButtonaddcat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonaddcatActionPerformed(evt);
            }
        });

        jButtonmodifCat.setBackground(new java.awt.Color(102, 153, 204));
        jButtonmodifCat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonmodifCat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Actions-view-refresh-icon.png"))); // NOI18N
        jButtonmodifCat.setText("Modifier");
        jButtonmodifCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonmodifCatActionPerformed(evt);
            }
        });

        jTextFieldCatLibelle.setBackground(new java.awt.Color(102, 153, 204));
        jTextFieldCatLibelle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldCatLibelle.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextFieldTva.setBackground(new java.awt.Color(102, 153, 204));
        jTextFieldTva.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextFieldTva.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldTva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTvaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel2.setText("Nom Catégorie");

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel8.setText("T.V.A");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Nombre de catégorie : ");

        jLabelNbCat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelNbCat.setText("00000");

        jTableCat.setBackground(new java.awt.Color(134, 185, 236));
        jTableCat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTableCat.setRowHeight(34);
        jTableCat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCatMouseClicked(evt);
            }
        });
        jScrollPane11.setViewportView(jTableCat);

        jLabelIdCat.setText("0");

        javax.swing.GroupLayout jPanelInputCategLayout = new javax.swing.GroupLayout(jPanelInputCateg);
        jPanelInputCateg.setLayout(jPanelInputCategLayout);
        jPanelInputCategLayout.setHorizontalGroup(
            jPanelInputCategLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInputCategLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInputCategLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator11)
                    .addGroup(jPanelInputCategLayout.createSequentialGroup()
                        .addGroup(jPanelInputCategLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelInputCategLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanelInputCategLayout.createSequentialGroup()
                                    .addComponent(jButtonaddcat, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonmodifCat, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelInputCategLayout.createSequentialGroup()
                                    .addGroup(jPanelInputCategLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGap(10, 10, 10)
                                    .addGroup(jPanelInputCategLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldTva, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldCatLibelle, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelIdCat, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jSeparator9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator8, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator10, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(jPanelInputCategLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelNbCat)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelInputCategLayout.setVerticalGroup(
            jPanelInputCategLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInputCategLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInputCategLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelInputCategLayout.createSequentialGroup()
                        .addComponent(jLabelIdCat, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelInputCategLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldCatLibelle, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelInputCategLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldTva, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelInputCategLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonmodifCat, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonaddcat, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanelInputCategLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabelNbCat)))
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
        );

        jTabbedPane1.addTab("Ajouter Catégorie", jPanelInputCateg);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void moveCursor() {
        KeyboardFocusManager manager = KeyboardFocusManager.getCurrentKeyboardFocusManager();
        manager.getFocusOwner().transferFocus();
    }

    private void configJTable() {
        jTableCat.getTableHeader().setPreferredSize(new Dimension(jTableCat.getTableHeader().getWidth(), 30));
        jTableCat.getTableHeader().setFont(new Font("Helvetica", Font.BOLD, 13));
        jTableCat.getTableHeader().setFont(new Font("Helvetica", Font.BOLD, 13));
        jTableCat.getColumnModel().getColumn(0).setPreferredWidth((50));
        jTableCat.getColumnModel().getColumn(1).setPreferredWidth(207);
        jTableCat.getColumnModel().getColumn(2).setPreferredWidth(50);
    }

    private void setProduitField(Produit prod) {

        jTextFieldCodeBarre.setText(prod.getCodebarre());
        jTextFieldLibelle.setText(prod.getLibelle());
        jTextFieldPrixAchat.setText(Double.toString(prod.getPrixAchat()));
        jTextFieldPrixVente.setText(Double.toString(prod.getPrixVente()));
        jTextFieldStock.setText(Integer.toString(prod.getQuantite()));
        System.out.println(prod.getNomCat());
        jComboBoxCategorie.setSelectedItem(prod.getNomCat());
    }
    private void jTextFieldStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldStockActionPerformed

    private void jButtonAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjouterActionPerformed
        Produit pro = new Produit();
        PrixDeVente ventePro = new PrixDeVente();

        if (fillProduitAtt(pro)) {
            fillPrixVentePro(ventePro);

            boolean ok = daoProd.insertProduit(pro);
            boolean prixVenteOk = daoPrixVente.insertPrixDeVente(ventePro);

            if (!ok || !prixVenteOk) {
                JOptionPane.showMessageDialog(null, "Insertion Impossible produit existe déjà!",
                        "Avertissement", JOptionPane.ERROR_MESSAGE);
            }

            clearProduitField();
            util.changeFocus(jTextFieldCodeBarre);

        }

    }//GEN-LAST:event_jButtonAjouterActionPerformed

    private void clearProduitField() {
        jTextFieldCodeBarre.setText("");
        jTextFieldLibelle.setText("");
        jTextFieldPrixAchat.setText("0.00");
        jTextFieldPrixVente.setText("");
        jTextFieldStock.setText("0");
    }

    private void fillPrixVentePro(PrixDeVente vente) {
        vente.setCodeBarre(jTextFieldCodeBarre.getText());
        vente.setPrix(Double.valueOf(jTextFieldPrixVente.getText()));
        vente.setIdMag(1);
        vente.setQuantite(Integer.valueOf(jTextFieldStock.getText()));
    }

    private boolean fillProduitAtt(Produit pro) {
        boolean isCreate = false;
        //Pk tu recupere pas le prix de vente
        if (!jTextFieldCodeBarre.getText().isEmpty() && !jTextFieldPrixAchat.getText().isEmpty()) {
            pro.setCodebarre(jTextFieldCodeBarre.getText());
            pro.setLibelle(jTextFieldLibelle.getText());
            pro.setPrixAchat(Double.valueOf(jTextFieldPrixAchat.getText()));
            pro.setIdCat(daoCat.getIdCategorie((String) jComboBoxCategorie.getSelectedItem()));
            isCreate = true;
        } else {
            JOptionPane.showMessageDialog(this, "Tous les champs nécessaire ne sont pas rempli", "Inane error",
                    JOptionPane.ERROR_MESSAGE);
        }

        return isCreate;

    }

    private void jButtonAjouterKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonAjouterKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

        }
    }//GEN-LAST:event_jButtonAjouterKeyPressed

    private void jButtonModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifierActionPerformed
        jTextFieldCodeBarre.setEditable(true);
        Produit pro = new Produit();
        PrixDeVente pdv = new PrixDeVente();
        fillProduitAtt(pro);
        fillPrixVentePro(pdv);

        boolean ok = daoProd.updateProduit(pro);
        boolean prixVenteOk = daoPrixVente.updateProduit(pdv);
        if (!ok || !prixVenteOk) {
            JOptionPane.showMessageDialog(null, "Update error !",
                    "Avertissement", JOptionPane.ERROR_MESSAGE);
        }

        clearProduitField();
    }//GEN-LAST:event_jButtonModifierActionPerformed

    private void jButtonModifierKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonModifierKeyPressed

    }//GEN-LAST:event_jButtonModifierKeyPressed

    private void jButtonaddcatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonaddcatActionPerformed
        // TODO add your handling code here:
        Categorie cat = new Categorie();
        cat.setIdCat(0);
        cat.setLibelle(jTextFieldCatLibelle.getText());
        cat.setTva(Double.parseDouble(jTextFieldTva.getText()));

        boolean ok = daoCat.insertCategorie(cat);
        if (!ok) {
            JOptionPane.showMessageDialog(null, "Insertion impossible !",
                    "Avertissement", JOptionPane.ERROR_MESSAGE);
        } else {
            Produit pro = new Produit();
            pro.setCodebarre(jTextFieldCatLibelle.getText());
            pro.setLibelle(jTextFieldCatLibelle.getText());
            pro.setIdCat(daoCat.lastId());
            pro.setLibelle(jTextFieldCatLibelle.getText());

            PrixDeVente vnt = new PrixDeVente();
            vnt.setCodeBarre(jTextFieldCatLibelle.getText());

            daoProd.insertProduit(pro);
            daoPrixVente.insertPrixDeVente(vnt);

        }

        clearFields();
        refresh();
    }//GEN-LAST:event_jButtonaddcatActionPerformed

    private void clearFields() {

        jTextFieldCatLibelle.setText("");
        jTextFieldTva.setText("");
    }
    private void jButtonmodifCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonmodifCatActionPerformed
        Categorie cat = new Categorie();

        if (!jTextFieldTva.getText().isEmpty() && !jTextFieldCatLibelle.getText().isEmpty()
                && !jLabelIdCat.getText().isEmpty()) {
            cat.setIdCat(Integer.parseInt(jLabelIdCat.getText()));
            cat.setLibelle(jTextFieldCatLibelle.getText());
            cat.setTva(Double.parseDouble(jTextFieldTva.getText()));
            if (daoCat.updateCategorie(cat)) {
                JDialogMessages msg = new JDialogMessages(this, "Modifié avec succès !", "");
            }
        } else {
            JDialogMessages msg = new JDialogMessages(this, "Modification échoué !!!!!!", "");
        }
        clearFields();
        jButtonaddcat.setEnabled(true);
    }//GEN-LAST:event_jButtonmodifCatActionPerformed

    private void jTextFieldTvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTvaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTvaActionPerformed

    private void jTextFieldCodeBarreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCodeBarreKeyPressed

        if (evt.getKeyChar() != '\n' && evt.getKeyChar() != '*'
                && evt.getKeyCode() != KeyEvent.VK_BACK_SPACE) {
            evt.consume();
        }

        if (evt.getKeyChar() == '\n') {
            moveCursor();
            Produit pro = daoProd.uneVenteProduit(jTextFieldCodeBarre.getText());
            if (pro != null) {
                JDialogMsgConfirm f = new JDialogMsgConfirm(this, "Modifier Produit", "Produit existe deja ");
                if (f.isConfirmer()) {

                    setProduitField(pro);
                    jTextFieldCodeBarre.setEditable(false);

                } else {
                    clearProduitField();
                }

            } else {
                moveCursor();
            }

        }
    }//GEN-LAST:event_jTextFieldCodeBarreKeyPressed

    private void jTextFieldCodeBarreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCodeBarreKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar())) {

            //evt.consume();
        }
    }//GEN-LAST:event_jTextFieldCodeBarreKeyTyped

    private void jTextFieldCodeBarreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodeBarreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodeBarreActionPerformed

    private void jTextFieldPrixAchatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPrixAchatKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar()) && evt.getKeyChar() != '.') {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldPrixAchatKeyTyped

    private void jTextFieldPrixVenteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPrixVenteKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar()) && evt.getKeyChar() != '.') {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldPrixVenteKeyTyped

    private void jTextFieldStockKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldStockKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldStockKeyTyped


    private void jTableCatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCatMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            Categorie cat = myModel.getMyList(jTableCat.getSelectedRow());
            jLabelIdCat.setText(String.valueOf(cat.getIdCat()));
            jTextFieldCatLibelle.setText(cat.getLibelle());
            jTextFieldTva.setText(String.valueOf(cat.getTva()));
            jButtonaddcat.setEnabled(false);

        }
    }//GEN-LAST:event_jTableCatMouseClicked

    private void jTextFieldPrixVenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrixVenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrixVenteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAjouter;
    private javax.swing.JButton jButtonModifier;
    private javax.swing.JButton jButtonaddcat;
    private javax.swing.JButton jButtonmodifCat;
    private javax.swing.JComboBox jComboBoxCategorie;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelIdCat;
    private javax.swing.JLabel jLabelNbArticle;
    private javax.swing.JLabel jLabelNbCat;
    private javax.swing.JPanel jPanelInputCateg;
    private javax.swing.JPanel jPanelProdPane;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableCat;
    private javax.swing.JTextField jTextFieldCatLibelle;
    private javax.swing.JTextField jTextFieldCodeBarre;
    private javax.swing.JTextField jTextFieldLibelle;
    private javax.swing.JFormattedTextField jTextFieldPrixAchat;
    private javax.swing.JFormattedTextField jTextFieldPrixVente;
    private javax.swing.JFormattedTextField jTextFieldStock;
    private javax.swing.JFormattedTextField jTextFieldTva;
    // End of variables declaration//GEN-END:variables
    private static final DAOCategorie daoCat = Factory.getDAOCategorie();
    private static final DAOPrixDeVente daoPrixVente = Factory.getDAOPrixDeVente();
    private static final DAOProduit daoProd = Factory.getDAOProduit();
    private static final JTableCategorie myModel = new JTableCategorie(daoCat.selectCategorie());
}
