/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import dao.DAOCategorie;
import dao.DAOProduit;
import factory.Factory;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.KeyEvent;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import model.JTableProduit;
import transferObject.Categorie;
import transferObject.Produit;

/**
 *
 * @author Himmat
 */
public class JPanelListeProduit extends javax.swing.JPanel {

    /**
     * Creates new form JPanelListeProduit
     */
    private int nbArticle = 0;
    private int nbCat = 0;
    public JPanelListeProduit() {
        initComponents();
        fillComboCategorie();
        configureJTable();
        this.nbArticle = daoProd.selectProduit().size();
        this.nbCat = daoCat.selectCategorie().size();
        jTextFieldSearch.requestFocusInWindow();

    }

    private void configureJTable() {
        jTableProduit.getTableHeader().setPreferredSize(new Dimension(jTableProduit.getTableHeader().getWidth(), 50));
        jTableProduit.getTableHeader().setFont(new Font("Helvetica", Font.BOLD, 13));
        jTableProduit.getColumnModel().getColumn(0).setPreferredWidth(100);
        jTableProduit.getColumnModel().getColumn(1).setPreferredWidth(150);
        jTableProduit.getColumnModel().getColumn(2).setPreferredWidth(20);
        jTableProduit.getColumnModel().getColumn(4).setPreferredWidth(20);
        jTableProduit.getColumnModel().getColumn(3).setPreferredWidth(100);

    }

    private void trie() {

        if (jComboBoxCategorie.getSelectedItem() != null) {
            myModelProduit.setMyList(daoProd.trie((String) jComboBoxCategorie.getSelectedItem()));
        }
    }

    private void fillComboCategorie() {
        jComboBoxCategorie.addItem("Tous");
        for (Categorie cat : daoCat.selectCategorie()) {
            jComboBoxCategorie.addItem(cat.getLibelle());
        }
        
    }

    public JTable getjTableProduit() {
        return jTableProduit;
    }

    public static JTableProduit getMyModelProduit() {
        return myModelProduit;
    }

    public static DAOProduit getDaoProd() {
        return daoProd;
    }

    public JButton getjButtonSearch() {
        return jButtonSearch;
    }

    public JComboBox getjComboBoxCategorie() {
        return jComboBoxCategorie;
    }

    public JTextField getjTextFieldSearch() {
        return jTextFieldSearch;
    }

    public int getNbArticle() {
        return nbArticle;
    }

    public int getNbCat() {
        return nbCat;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTableProduit = new JTable(myModelProduit);
        jButtonSearch = new javax.swing.JButton();
        jComboBoxCategorie = new javax.swing.JComboBox();
        jTextFieldSearch = new javax.swing.JTextField();
        jButtonAdd = new javax.swing.JButton();
        jButtonModifier = new javax.swing.JButton();
        jButtonSupprimer = new javax.swing.JButton();

        setBackground(new java.awt.Color(175, 210, 245));

        jTableProduit.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jTableProduit.setGridColor(new java.awt.Color(204, 255, 204));
        jTableProduit.setRowHeight(34);
        jScrollPane2.setViewportView(jTableProduit);

        jButtonSearch.setBackground(new java.awt.Color(102, 153, 204));
        jButtonSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search-green-neon-icon.png"))); // NOI18N
        jButtonSearch.setText("Chercher");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });

        jComboBoxCategorie.setBackground(new java.awt.Color(204, 255, 204));
        jComboBoxCategorie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCategorieActionPerformed(evt);
            }
        });

        jTextFieldSearch.setBackground(new java.awt.Color(134, 185, 236));
        jTextFieldSearch.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jTextFieldSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldSearchKeyPressed(evt);
            }
        });

        jButtonAdd.setBackground(new java.awt.Color(102, 153, 204));
        jButtonAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add-icon.png"))); // NOI18N
        jButtonAdd.setText("Ajouter");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonModifier.setBackground(new java.awt.Color(102, 153, 204));
        jButtonModifier.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonModifier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Actions-view-refresh-icon.png"))); // NOI18N
        jButtonModifier.setText("Modifier");
        jButtonModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifierActionPerformed(evt);
            }
        });

        jButtonSupprimer.setBackground(new java.awt.Color(102, 153, 204));
        jButtonSupprimer.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonSupprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete-icon.png"))); // NOI18N
        jButtonSupprimer.setText("Supprimer");
        jButtonSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSupprimerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 777, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonModifier, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxCategorie, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxCategorie)
                    .addComponent(jTextFieldSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                    .addComponent(jButtonSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSupprimer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonModifier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxCategorieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCategorieActionPerformed
        // TODO add your handling code here:
        trie();
    }//GEN-LAST:event_jComboBoxCategorieActionPerformed

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        // TODO add your handling code here:
        rechercherProduit();
    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void jTextFieldSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSearchKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyChar() != '\n' && evt.getKeyChar() != java.awt.event.KeyEvent.VK_BACK_SPACE) {
            evt.consume();
        }
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            rechercherProduit();
        }
    }//GEN-LAST:event_jTextFieldSearchKeyPressed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        // TODO add your handling code here:
        JDialogAjouterProduit f = new JDialogAjouterProduit(null, "ajouter");
        f.setVisible(true);
        myModelProduit.setMyList(daoProd.selectProduit());

    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifierActionPerformed
        if (jTableProduit.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Sélectionnez d'abord une ligne svp !",
                    "Avertissement", JOptionPane.ERROR_MESSAGE);
        } else {

            Produit prod = myModelProduit.getMyList(jTableProduit.getSelectedRow());
            JDialogAjouterProduit f = new JDialogAjouterProduit(null, "ajouter", prod);
            f.setVisible(true);
            myModelProduit.setMyList(daoProd.selectProduit());

        }
    }//GEN-LAST:event_jButtonModifierActionPerformed

    private void jButtonSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSupprimerActionPerformed
        // TODO add your handling code here:
        if (jTableProduit.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Sélectionnez d'abord une ligne svp !",
                    "Avertissement", JOptionPane.ERROR_MESSAGE);
        } else {
            int rep = JOptionPane.showConfirmDialog(null, "Voulez-vous vraiment supprimer "
                    + myModelProduit.getValueAt(jTableProduit.getSelectedRow(), 0) + " ?",
                    "Confirmation", JOptionPane.YES_NO_OPTION);
            if (rep == JOptionPane.YES_OPTION) {
                Produit prod = myModelProduit.getMyList(jTableProduit.getSelectedRow());
                daoProd.deleteProduit(prod.getCodebarre());
                myModelProduit.setMyList(daoProd.selectProduit());
            }
        }
    }//GEN-LAST:event_jButtonSupprimerActionPerformed
    private void rechercherProduit() {
        String rech = jTextFieldSearch.getText();
        if (rech != null) {
            myModelProduit.setMyList(daoProd.searchProduit(rech));
        }
        jTextFieldSearch.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonModifier;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JButton jButtonSupprimer;
    private javax.swing.JComboBox jComboBoxCategorie;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableProduit;
    private javax.swing.JTextField jTextFieldSearch;
    // End of variables declaration//GEN-END:variables
    private static final DAOProduit daoProd = Factory.getDAOProduit();
    private static final JTableProduit myModelProduit = new JTableProduit(daoProd.selectProduit());
    private static final DAOCategorie daoCat = Factory.getDAOCategorie();

}
