/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package presentation;

import java.awt.AWTException;
import java.awt.Robot;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Himmat
 */
public class KeyPad extends javax.swing.JPanel {

    /**
     * Creates new form PAD
     */
    public KeyPad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPad = new javax.swing.JPanel();
        jButtonNum3 = new javax.swing.JButton();
        jButtonNum1 = new javax.swing.JButton();
        jButtonNum2 = new javax.swing.JButton();
        jButtonNum6 = new javax.swing.JButton();
        jButtonNum4 = new javax.swing.JButton();
        jButtonNum5 = new javax.swing.JButton();
        jButtonNum7 = new javax.swing.JButton();
        jButtonNum9 = new javax.swing.JButton();
        jButtonNum8 = new javax.swing.JButton();
        jButtonNum0 = new javax.swing.JButton();
        jButtonNumFois = new javax.swing.JButton();
        jButtonNumVir = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(255, 220));

        jPanelPad.setLayout(null);

        jButtonNum3.setBackground(new java.awt.Color(204, 255, 153));
        jButtonNum3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonNum3.setBorderPainted(false);
        jButtonNum3.setContentAreaFilled(false);
        jButtonNum3.setFocusPainted(false);
        jButtonNum3.setFocusable(false);
        jButtonNum3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/onClick.png"))); // NOI18N
        jButtonNum3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNum3ActionPerformed(evt);
            }
        });
        jPanelPad.add(jButtonNum3);
        jButtonNum3.setBounds(170, 0, 72, 44);

        jButtonNum1.setBackground(new java.awt.Color(204, 255, 153));
        jButtonNum1.setAutoscrolls(true);
        jButtonNum1.setBorder(null);
        jButtonNum1.setBorderPainted(false);
        jButtonNum1.setContentAreaFilled(false);
        jButtonNum1.setFocusPainted(false);
        jButtonNum1.setFocusable(false);
        jButtonNum1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/onClick.png"))); // NOI18N
        jButtonNum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNum1ActionPerformed(evt);
            }
        });
        jPanelPad.add(jButtonNum1);
        jButtonNum1.setBounds(0, 0, 80, 44);

        jButtonNum2.setBackground(new java.awt.Color(204, 255, 153));
        jButtonNum2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonNum2.setBorderPainted(false);
        jButtonNum2.setContentAreaFilled(false);
        jButtonNum2.setFocusPainted(false);
        jButtonNum2.setFocusable(false);
        jButtonNum2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/onClick.png"))); // NOI18N
        jButtonNum2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNum2ActionPerformed(evt);
            }
        });
        jPanelPad.add(jButtonNum2);
        jButtonNum2.setBounds(90, 0, 72, 44);

        jButtonNum6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonNum6.setBorderPainted(false);
        jButtonNum6.setContentAreaFilled(false);
        jButtonNum6.setFocusPainted(false);
        jButtonNum6.setFocusable(false);
        jButtonNum6.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/onClick.png"))); // NOI18N
        jButtonNum6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNum6ActionPerformed(evt);
            }
        });
        jPanelPad.add(jButtonNum6);
        jButtonNum6.setBounds(170, 50, 72, 44);

        jButtonNum4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonNum4.setBorderPainted(false);
        jButtonNum4.setContentAreaFilled(false);
        jButtonNum4.setFocusPainted(false);
        jButtonNum4.setFocusable(false);
        jButtonNum4.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/onClick.png"))); // NOI18N
        jButtonNum4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNum4ActionPerformed(evt);
            }
        });
        jPanelPad.add(jButtonNum4);
        jButtonNum4.setBounds(0, 50, 80, 44);

        jButtonNum5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonNum5.setBorderPainted(false);
        jButtonNum5.setContentAreaFilled(false);
        jButtonNum5.setFocusPainted(false);
        jButtonNum5.setFocusable(false);
        jButtonNum5.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/onClick.png"))); // NOI18N
        jButtonNum5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNum5ActionPerformed(evt);
            }
        });
        jPanelPad.add(jButtonNum5);
        jButtonNum5.setBounds(90, 50, 72, 44);

        jButtonNum7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonNum7.setBorderPainted(false);
        jButtonNum7.setContentAreaFilled(false);
        jButtonNum7.setFocusPainted(false);
        jButtonNum7.setFocusable(false);
        jButtonNum7.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/onClick.png"))); // NOI18N
        jButtonNum7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNum7ActionPerformed(evt);
            }
        });
        jPanelPad.add(jButtonNum7);
        jButtonNum7.setBounds(0, 100, 80, 50);

        jButtonNum9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonNum9.setBorderPainted(false);
        jButtonNum9.setContentAreaFilled(false);
        jButtonNum9.setFocusPainted(false);
        jButtonNum9.setFocusable(false);
        jButtonNum9.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/onClick.png"))); // NOI18N
        jButtonNum9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNum9ActionPerformed(evt);
            }
        });
        jPanelPad.add(jButtonNum9);
        jButtonNum9.setBounds(170, 100, 72, 50);

        jButtonNum8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonNum8.setBorderPainted(false);
        jButtonNum8.setContentAreaFilled(false);
        jButtonNum8.setFocusPainted(false);
        jButtonNum8.setFocusable(false);
        jButtonNum8.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/onClick.png"))); // NOI18N
        jButtonNum8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNum8ActionPerformed(evt);
            }
        });
        jPanelPad.add(jButtonNum8);
        jButtonNum8.setBounds(90, 100, 72, 50);

        jButtonNum0.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonNum0.setBorderPainted(false);
        jButtonNum0.setContentAreaFilled(false);
        jButtonNum0.setFocusPainted(false);
        jButtonNum0.setFocusable(false);
        jButtonNum0.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/onClick.png"))); // NOI18N
        jButtonNum0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNum0ActionPerformed(evt);
            }
        });
        jPanelPad.add(jButtonNum0);
        jButtonNum0.setBounds(90, 160, 72, 40);

        jButtonNumFois.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonNumFois.setBorderPainted(false);
        jButtonNumFois.setContentAreaFilled(false);
        jButtonNumFois.setFocusPainted(false);
        jButtonNumFois.setFocusable(false);
        jButtonNumFois.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/onClick.png"))); // NOI18N
        jButtonNumFois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumFoisActionPerformed(evt);
            }
        });
        jPanelPad.add(jButtonNumFois);
        jButtonNumFois.setBounds(0, 160, 80, 40);

        jButtonNumVir.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonNumVir.setBorderPainted(false);
        jButtonNumVir.setContentAreaFilled(false);
        jButtonNumVir.setFocusPainted(false);
        jButtonNumVir.setFocusable(false);
        jButtonNumVir.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/onClick.png"))); // NOI18N
        jButtonNumVir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumVirActionPerformed(evt);
            }
        });
        jPanelPad.add(jButtonNumVir);
        jButtonNumVir.setBounds(170, 160, 72, 40);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pad.png"))); // NOI18N
        jPanelPad.add(jLabel7);
        jLabel7.setBounds(4, 0, 240, 200);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPad, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPad, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNum3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNum3ActionPerformed
        padEvent(KeyEvent.VK_NUMPAD3);
    }//GEN-LAST:event_jButtonNum3ActionPerformed

    private void jButtonNum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNum1ActionPerformed
        padEvent(KeyEvent.VK_NUMPAD1);
    }//GEN-LAST:event_jButtonNum1ActionPerformed

    private void jButtonNum2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNum2ActionPerformed
        padEvent(KeyEvent.VK_NUMPAD2);
    }//GEN-LAST:event_jButtonNum2ActionPerformed

    private void jButtonNum6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNum6ActionPerformed
        padEvent(KeyEvent.VK_NUMPAD6);
    }//GEN-LAST:event_jButtonNum6ActionPerformed

    private void jButtonNum4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNum4ActionPerformed
        padEvent(KeyEvent.VK_NUMPAD4);
    }//GEN-LAST:event_jButtonNum4ActionPerformed

    private void jButtonNum5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNum5ActionPerformed
        padEvent(KeyEvent.VK_NUMPAD5);
    }//GEN-LAST:event_jButtonNum5ActionPerformed

    private void jButtonNum7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNum7ActionPerformed
        padEvent(KeyEvent.VK_NUMPAD7);
    }//GEN-LAST:event_jButtonNum7ActionPerformed

    private void jButtonNum9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNum9ActionPerformed
        padEvent(KeyEvent.VK_NUMPAD9);
    }//GEN-LAST:event_jButtonNum9ActionPerformed

    private void jButtonNum8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNum8ActionPerformed
        padEvent(KeyEvent.VK_NUMPAD8);
    }//GEN-LAST:event_jButtonNum8ActionPerformed

    private void jButtonNum0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNum0ActionPerformed
        padEvent(KeyEvent.VK_NUMPAD0);
    }//GEN-LAST:event_jButtonNum0ActionPerformed

    private void jButtonNumFoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumFoisActionPerformed
        // TODO add your handling code here:
        padEvent(KeyEvent.VK_BACK_SPACE);
    }//GEN-LAST:event_jButtonNumFoisActionPerformed

    private void jButtonNumVirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumVirActionPerformed
        padEvent(KeyEvent.VK_DECIMAL);
    }//GEN-LAST:event_jButtonNumVirActionPerformed
private void padEvent(int key) {
        Robot robot;
        try {
            robot = new Robot();
            robot.keyPress(key);
            robot.keyRelease(key);
        } catch (AWTException ex) {
            Logger.getLogger(JFVente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNum0;
    private javax.swing.JButton jButtonNum1;
    private javax.swing.JButton jButtonNum2;
    private javax.swing.JButton jButtonNum3;
    private javax.swing.JButton jButtonNum4;
    private javax.swing.JButton jButtonNum5;
    private javax.swing.JButton jButtonNum6;
    private javax.swing.JButton jButtonNum7;
    private javax.swing.JButton jButtonNum8;
    private javax.swing.JButton jButtonNum9;
    private javax.swing.JButton jButtonNumFois;
    private javax.swing.JButton jButtonNumVir;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanelPad;
    // End of variables declaration//GEN-END:variables
}
