/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ticket;

import java.io.*;
import org.jdom2.*;
import org.jdom2.input.*;
import java.util.List;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.print.DocFlavor;
import javax.print.PrintService;
import javax.print.PrintServiceLookup;
import javax.print.attribute.HashPrintRequestAttributeSet;
import javax.print.attribute.PrintRequestAttributeSet;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.jdom2.output.Format;
import org.jdom2.output.XMLOutputter;

/**
 *
 * @author Ilias
 */
public class Configuration extends javax.swing.JDialog {

    private Element racine;
    private org.jdom2.Document document = null;

    /**
     * Creates new form Configuration
     */
    public Configuration(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        SAXBuilder sxb = new SAXBuilder();
        try {
            //On crée un nouveau document JDOM avec en argument le fichier XML
            //Le parsing est terminé ;)
            document = sxb.build(new File("ticket.xml"));
        } catch (Exception e) {
            System.out.println("Erreur");
        }
        initialiseHeader();
        initialierFooter();
        initialiserLogo();
        initialisercombox();
    }

    public void initialisercombox() {
        PrintRequestAttributeSet pras = new HashPrintRequestAttributeSet();
        DocFlavor flavor = DocFlavor.INPUT_STREAM.AUTOSENSE;
        String mime = flavor.getMimeType();
        PrintService printService[] = PrintServiceLookup.lookupPrintServices(flavor, pras);
        
        for (int i = 0; i < printService.length; i++) {
            combobox_printers.addItem(printService[i].getName());
        }
        
        combobox_printers.setSelectedItem(getPrint());
    }
     
        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textarea_head = new javax.swing.JTextArea();
        label_head = new javax.swing.JLabel();
        label_footer = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textarea_footer = new javax.swing.JTextArea();
        label_logo = new javax.swing.JLabel();
        button_parcourir = new javax.swing.JButton();
        textfield_logo = new javax.swing.JTextField();
        sauvegarder_header = new javax.swing.JButton();
        sauvegarder_footer = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        combobox_printers = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        textarea_head.setColumns(20);
        textarea_head.setRows(5);
        jScrollPane1.setViewportView(textarea_head);

        label_head.setText("Head:");

        label_footer.setText("Footer:");

        textarea_footer.setColumns(20);
        textarea_footer.setRows(5);
        jScrollPane2.setViewportView(textarea_footer);

        label_logo.setText("Logo:");

        button_parcourir.setText("Parcourir....");
        button_parcourir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_parcourirActionPerformed(evt);
            }
        });

        sauvegarder_header.setText("Sauvegarder");
        sauvegarder_header.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sauvegarder_headerActionPerformed(evt);
            }
        });

        sauvegarder_footer.setText("Sauvegarder");
        sauvegarder_footer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sauvegarder_footerActionPerformed(evt);
            }
        });

        jButton1.setText("Terminer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Choix imprimante:");

        combobox_printers.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " "}));
        combobox_printers.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combobox_printersItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_footer)
                            .addComponent(label_head, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_logo))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sauvegarder_header)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(sauvegarder_footer)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(textfield_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(46, 46, 46)
                                    .addComponent(button_parcourir, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(44, 44, 44)
                        .addComponent(combobox_printers, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(combobox_printers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label_logo)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textfield_logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(button_parcourir)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_head)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(sauvegarder_header)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_footer)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sauvegarder_footer)
                    .addComponent(jButton1))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_parcourirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_parcourirActionPerformed
        // TODO add your handling code here:
        //création dun nouveau filechosser
        FileNameExtensionFilter imagesFilter = new FileNameExtensionFilter("Images", "bmp", "gif", "jpg", "jpeg", "png");
        JFileChooser chooser = new JFileChooser();

        //intitulé du bouton
//        chooser.setApproveButtonText("Choix de l'image");
        chooser.setFileFilter(imagesFilter);
//        
//        chooser.showOpenDialog(null);
        if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            textfield_logo.setText(chooser.getSelectedFile().getAbsolutePath());

            copier(chooser.getSelectedFile(), new File(chooser.getSelectedFile().getName()));
            modifierXml(chooser.getSelectedFile().getName(), "logo");
        }
    }//GEN-LAST:event_button_parcourirActionPerformed

    private void sauvegarder_headerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sauvegarder_headerActionPerformed
        // TODO add your handling code here:
        modifierXml(textarea_head.getText(), "head");
    }//GEN-LAST:event_sauvegarder_headerActionPerformed

    private void sauvegarder_footerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sauvegarder_footerActionPerformed
        // TODO add your handling code here:
        modifierXml(textarea_footer.getText(), "footer");
    }//GEN-LAST:event_sauvegarder_footerActionPerformed

    private void combobox_printersItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combobox_printersItemStateChanged
        // TODO add your handling code here:
        modifierXml(combobox_printers.getSelectedItem().toString(), "printer");
    }//GEN-LAST:event_combobox_printersItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
        
    private String getPrint() {
      
            racine = document.getRootElement();
            Element baliseElm = racine.getChild("printer");
            List listline = baliseElm.getChildren();
            Element elm =  (Element) listline.get(0);
            return elm.getText();
          
    }
    
    
    private void modifierXml(String text, String balise) {
        try {
            racine = document.getRootElement();
            Element baliseElm = racine.getChild(balise);
            List listline = baliseElm.getChildren();
            String[] valueLine = text.split("\n", -1);
            //On crée un Iterator sur notre liste
            Iterator i = listline.iterator();
            int j = 0;
            while (i.hasNext()) {
                Element courant = (Element) i.next();
                courant.setText(valueLine[j]);
                j++;
            }
            XMLOutputter sortie = new XMLOutputter(Format.getPrettyFormat());
            sortie.output(document, new FileOutputStream("ticket.xml"));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Configuration.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Configuration.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void initialiseHeader() {
        String t = initialiserTextArea("head");
        textarea_head.setText(t);
    }

    private void initialiserLogo() {

        String t = initialiserTextArea("logo");
        textfield_logo.setText(t);
    }

    private void initialierFooter() {
        String t = initialiserTextArea("footer");
        textarea_footer.setText(t);
    }

    private String initialiserTextArea(String balise) {
        racine = document.getRootElement();
        Element head = racine.getChild(balise);
        List listline = head.getChildren();

        //On crée un Iterator sur notre liste
        Iterator i = listline.iterator();
        String text = "";
        while (i.hasNext()) {
            //On recrée l'Element courant à chaque tour de boucle afin de
            //pouvoir utiliser les méthodes propres aux Element comme :
            //sélectionner un nœud fils, modifier du texte, etc...
            Element courant = (Element) i.next();

            //On affiche le nom de l’élément courant
            // System.out.println(courant.getChild("line").getText());
            text += courant.getText() + "\n";

        }
        return text;
    }

    private boolean copier(File source, File destination) { //Methode permettant la copie d'un fichier
        boolean resultat = false;

// Declaration des flux
        java.io.FileInputStream sourceFile = null;
        java.io.FileOutputStream destinationFile = null;
        try {
// Création du fichier :
            destination.createNewFile();
// Ouverture des flux
            sourceFile = new java.io.FileInputStream(source);
            destinationFile = new java.io.FileOutputStream(destination);
// Lecture par segment de 0.5Mo
            byte buffer[] = new byte[512 * 1024];
            int nbLecture;
            while ((nbLecture = sourceFile.read(buffer)) != -1) {
                destinationFile.write(buffer, 0, nbLecture);
            }

// Copie réussie
            resultat = true;
        } catch (java.io.FileNotFoundException f) {
        } catch (java.io.IOException e) {
        } finally {
// Quoi qu'il arrive, on ferme les flux
            try {
                sourceFile.close();
            } catch (Exception e) {
            }
            try {
                destinationFile.close();
            } catch (Exception e) {
            }
        }
        return (resultat);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_parcourir;
    private javax.swing.JComboBox combobox_printers;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label_footer;
    private javax.swing.JLabel label_head;
    private javax.swing.JLabel label_logo;
    private javax.swing.JButton sauvegarder_footer;
    private javax.swing.JButton sauvegarder_header;
    private javax.swing.JTextArea textarea_footer;
    private javax.swing.JTextArea textarea_head;
    private javax.swing.JTextField textfield_logo;
    // End of variables declaration//GEN-END:variables
}
