/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ticket;

import Utile.PeripheriqueXML;

/**
 *
 * @author Fawad
 */
public class ConfigImprimente extends javax.swing.JPanel {

    private PeripheriqueXML peri;

    /**
     * Creates new form ConfigImprimente
     */
    public ConfigImprimente() {
        
        initComponents();
        peri = new PeripheriqueXML();
        initialiseHeader();
        initialierFooter();
        textarea_footerLed.setText(peri.getBalise(peri.FOOTER_LED));
        textarea_headLed.setText(peri.getBalise(peri.HEAD_LED));
        
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textarea_head = new javax.swing.JTextArea();
        label_head = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textarea_footer = new javax.swing.JTextArea();
        label_footer = new javax.swing.JLabel();
        sauvegarder_header = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        textarea_headLed = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        textarea_footerLed = new javax.swing.JTextArea();
        sauvegarder_header1 = new javax.swing.JButton();
        label_head1 = new javax.swing.JLabel();
        label_footer1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        jTabbedPane1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        textarea_head.setBackground(new java.awt.Color(134, 185, 236));
        textarea_head.setColumns(20);
        textarea_head.setRows(5);
        jScrollPane1.setViewportView(textarea_head);

        label_head.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        label_head.setText("Head:");

        textarea_footer.setBackground(new java.awt.Color(134, 185, 236));
        textarea_footer.setColumns(20);
        textarea_footer.setRows(5);
        jScrollPane2.setViewportView(textarea_footer);

        label_footer.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        label_footer.setText("Footer:");

        sauvegarder_header.setBackground(new java.awt.Color(134, 185, 236));
        sauvegarder_header.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/kaydet.png"))); // NOI18N
        sauvegarder_header.setText("Sauvegarder");
        sauvegarder_header.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sauvegarder_headerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sauvegarder_header, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_head, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label_footer)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(59, 59, 59))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))))
                .addContainerGap(427, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label_head)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label_footer)
                        .addGap(1, 1, 1)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(sauvegarder_header, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ticket de Caisse", jPanel1);

        textarea_headLed.setBackground(new java.awt.Color(134, 185, 236));
        textarea_headLed.setColumns(20);
        textarea_headLed.setRows(5);
        jScrollPane3.setViewportView(textarea_headLed);

        textarea_footerLed.setBackground(new java.awt.Color(134, 185, 236));
        textarea_footerLed.setColumns(20);
        textarea_footerLed.setRows(5);
        jScrollPane4.setViewportView(textarea_footerLed);

        sauvegarder_header1.setBackground(new java.awt.Color(134, 185, 236));
        sauvegarder_header1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/kaydet.png"))); // NOI18N
        sauvegarder_header1.setText("Sauvegarder");
        sauvegarder_header1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sauvegarder_header1ActionPerformed(evt);
            }
        });

        label_head1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        label_head1.setText("Welcome Message:");

        label_footer1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        label_footer1.setText("Bye Message :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_footer1)
                            .addComponent(label_head1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(sauvegarder_header1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(396, 396, 396))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(label_head1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(label_footer1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(sauvegarder_header1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Afficheur Led", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sauvegarder_headerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sauvegarder_headerActionPerformed
        // TODO add your handling code here:
        peri.modifierXml(textarea_head.getText(), peri.HEAD);
        peri.modifierXml(textarea_footer.getText(), peri.FOOTER);
    }//GEN-LAST:event_sauvegarder_headerActionPerformed

    private void sauvegarder_header1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sauvegarder_header1ActionPerformed
        // TODO add your handling code here:
        peri.modifierXml(textarea_headLed.getText(), peri.HEAD_LED);
        peri.modifierXml(textarea_footerLed.getText(), peri.FOOTER_LED);
    }//GEN-LAST:event_sauvegarder_header1ActionPerformed


   
    private void initialiseHeader() {
        String t = peri.getBalise(peri.HEAD);
        textarea_head.setText(t);
    }

   

    private void initialierFooter() {
        String t = peri.getBalise(peri.FOOTER);
        textarea_footer.setText(t);
    }

   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel label_footer;
    private javax.swing.JLabel label_footer1;
    private javax.swing.JLabel label_head;
    private javax.swing.JLabel label_head1;
    private javax.swing.JButton sauvegarder_header;
    private javax.swing.JButton sauvegarder_header1;
    private javax.swing.JTextArea textarea_footer;
    private javax.swing.JTextArea textarea_footerLed;
    private javax.swing.JTextArea textarea_head;
    private javax.swing.JTextArea textarea_headLed;
    // End of variables declaration//GEN-END:variables
}
